// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcknhrcezuqeurkypqmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZja25ocmNlenVxZXVya3lwcW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjQyOTYsImV4cCI6MjA2MTQ0MDI5Nn0.EJJJqHh3yDhffC42ZkMQzRw9Mu8vOqkbNi082TaBmbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});