// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlmfwuioaisfhggiyehx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbWZ3dWlvYWlzZmhnZ2l5ZWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzQzNTIsImV4cCI6MjA3MDI1MDM1Mn0.SfmWnOyxyhRyiJmivA4nogqBRgFXyd2XX1mL8VFGzoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});